name: CD

on:
  push:
    branches:
    - release/*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: config git
      run: |
        git config --global user.email $GITHUB_ACTOR"@github.com"
        git config --global user.name $GITHUB_ACTOR

    - name: Cache node modules
      uses: actions/cache@v2
      id: cache-node-modules
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'

    - run: npm install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'

    - run: npm test
    - run: npm version $(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - run: git push
    - run: git push --tags

    - name: merge master
      run: |
        VERSION=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
        git checkout master
        git merge --no-ff $GITHUB_REF -m $VERSION
        git push

    - name: merge develop
      run: |

