name: CD

on:
  push:
    branches:
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git config --global user.email "csosaur@gmail.com"
    - run: git config --global user.name "Gunmer@github"
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm test
    - run: npm version $(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
