name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Download code

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v1
        name: Setup node (last LTS)
        with:
          node-version: 12.x

      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: npm run lint
      - run: npm run coverage

      - uses: codecov/codecov-action@v1
        name: Update coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: true
